baseURL: "https://www.kinjo.tech/"
title: Keisei Kinjo (JC)'s Blog
copyright: "© 2026 kinjo.tech"
theme: minimal

enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: G-FRYQ5R2WW9

params:
  env: production
  title: Keisei Kinjo (JC)'s Blog
  description: Keisei Kinjo (JC)'s Blog
  keywords:
    - Blog
    - Portfolio
  author: JC
  DateFormat: "January 2, 2006"

  ShowShareButtons: true
  ShareButtons:
    - "linkedin"
    - "twitter"
    - "facebook"
    - "reddit"
    - "telegram"
  ShowCodeCopyButtons: true
  UseHugoToc: true
  comments: true
  showtoc: true

  assets:
    favicon: favicon.png
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple_touch_icon.png

  label:
    icon: /favicon.png
    iconHeight: 45

  socialIcons:
    - name: email
      url: "mailto:jci@tutamail.com"
    - name: github
      url: "https://github.com/jckinjo"
    - name: linkedin
      url: "https://www.linkedin.com/in/kinjok/"
    - name: rss
      url: "/index.xml"

outputs:
  home:
    - HTML
    - RSS

menu:
  main:
    - identifier: about
      name: About
      url: /
      weight: 10
    - identifier: writing
      name: Writing
      url: /writing/
      weight: 20
    - identifier: reading
      name: Reading
      url: /posts/reading/
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

taxonomies: {}
